name: Build Quarkus Docker Image (Gradle)

on:
  push:
    branches: [ feat/basic-image_build_publish ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Quarkus app
        run: ./gradlew clean build -x test

      - name: Build Docker image (JVM)
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t quarkus-app:latest .
