name: Build Quarkus Docker Image (Gradle)

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ feat/basic-image_build_publish ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build Quarkus app
        run: ./gradlew clean build -x test

      - name: Build Docker image (JVM)
        run: |
          docker build -f src/main/docker/Dockerfile.jvm -t quarkus-app:latest .
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag & push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/quarkus-app
          docker tag quarkus-app:latest $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
